---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tranga.fullname" . }}-web
  labels:
    {{- include "tranga.labels" . | nindent 4 }}
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;

    error_log  /var/log/nginx/error.log notice;
    pid        /tmp/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        client_body_temp_path /tmp/client_temp;
        proxy_temp_path       /tmp/proxy_temp_path;
        fastcgi_temp_path     /tmp/fastcgi_temp;
        uwsgi_temp_path       /tmp/uwsgi_temp;
        scgi_temp_path        /tmp/scgi_temp;

        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        gzip on;
        gzip_min_length  1100;
        gzip_buffers     4 8k;
        gzip_types       text/plain;

        include /etc/nginx/conf.d/*.conf;
    }
  default.conf: |
    server {
        listen       8080 default_server;
        listen  [::]:8080 default_server;

        http2  on;

        server_name  _;

        access_log  /dev/stdout  main;
        error_log  /dev/stderr;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /api {
            proxy_pass_request_headers on;
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://127.0.0.1:6531;
        }
        
        location /swagger {
            proxy_pass_request_headers on;
            proxy_pass http://127.0.0.1:6531;
        }

        location /v2 {
            proxy_pass_request_headers on;
            proxy_pass http://127.0.0.1:6531;
        }

        location /_ipx/_/api{
            proxy_pass_request_headers on;
            rewrite ^/_ipx/_/api/(.*)$ /$1 break;
            proxy_pass http://127.0.0.1:6531;
        }
        
        # redirect server error pages to the static page /504.html
        #
        error_page   404  /404.html;
        location = /404.html {
            root   /usr/share/nginx/html;
        }

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
