apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tranga.fullname" . }}
  labels:
    {{- include "tranga.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tranga.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tranga.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tranga.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-api
          {{- with .Values.api.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.postgresql.hostname }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.databaseName }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username }}
            {{- if not (empty .Values.postgresql.password) }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.password.name }}
                  key: {{ .Values.postgresql.password.key }}
            {{- end }}
            {{- if not (empty .Values.flaresolverrUrl) }}
            - name: FLARESOLVERR_URL
              value: {{ .Values.flaresolverrUrl }}
            {{- end }}
          ports:
            - name: api
              containerPort: 6531
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v2/Manga
              port: api
          readinessProbe:
            httpGet:
              path: /v2/Manga
              port: api
          {{- with .Values.api.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ .Chart.Name }}-api-library
              mountPath: /Manga
            - name: {{ .Chart.Name }}-api-config
              mountPath: /usr/share/tranga-api
            - name: {{ .Chart.Name }}-api-tmp
              mountPath: /tmp
          {{- with .Values.api.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: {{ .Chart.Name }}-web
          {{- with .Values.web.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          env:
            - name: API_URL
              value: http://127.0.0.1:6531/api
            - name: NGINX_ENVSUBST_TEMPLATE_DIR
              value: /doesntexists
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- with .Values.web.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ .Chart.Name }}-web-cache
              mountPath: /var/cache/nginx
            - name: {{ .Chart.Name }}-web-nginx-run
              mountPath: /var/run
            - name: {{ .Chart.Name }}-web-nginx
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: {{ .Chart.Name }}-web-nginx
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: {{ .Chart.Name }}-web-tmp
              mountPath: /tmp
          {{- with .Values.web.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: {{ .Chart.Name }}-api-config
          {{- if .Values.persistence.config.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.config.claimName }}{{ .Values.persistence.config.claimName }}{{- else }}{{ template "tranga.fullname" . }}-config{{- end }}
          {{- else }}
          emptyDir:
            sizeLimit: {{ .Values.persistence.config.size }}
          {{- end }}
        - name: {{ .Chart.Name }}-api-library
          {{- if .Values.persistence.library.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.library.claimName }}{{ .Values.persistence.library.claimName }}{{- else }}{{ template "tranga.fullname" . }}-library{{- end }}
          {{- else }}
          emptyDir:
            sizeLimit: {{ .Values.persistence.library.size }}
          {{- end }}
        - name: {{ .Chart.Name }}-api-tmp
          emptyDir:
            sizeLimit: 10Mi
        - name: {{ .Chart.Name }}-web-cache
          emptyDir:
            sizeLimit: 10Mi
        - name: {{ .Chart.Name }}-web-nginx-run
          emptyDir:
            sizeLimit: 10Mi
        - name: {{ .Chart.Name }}-web-nginx
          configMap:
            name: {{ include "tranga.fullname" . }}-web
        - name: {{ .Chart.Name }}-web-tmp
          emptyDir:
            sizeLimit: 10Mi
      {{- with .Values.api.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
