{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.claimName) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tranga.fullname" . }}-config
  labels:
    {{- include "tranga.labels" . | nindent 4 }}
    {{- with .Values.persistence.config.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.persistence.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}
  {{- with .Values.persistence.config.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}

{{- if and .Values.persistence.library.enabled (not .Values.persistence.library.claimName) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tranga.fullname" . }}-library
  labels:
    {{- include "tranga.labels" . | nindent 4 }}
    {{- with .Values.persistence.library.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.persistence.library.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.library.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.library.size | quote }}
  {{- with .Values.persistence.library.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
